import pathlib
NL = chr(10)
BASE = pathlib.Path("validation/gauquelin")
BASE.mkdir(parents=True, exist_ok=True)

def write_file(name, lines):
    (BASE / name).write_text(NL.join(lines), encoding="utf-8")
    print(f"Wrote {name} ({len(lines)} lines)")

f01 = [
    'from __future__ import annotations',
    '"""',
    '01_parse_gauquelin.py - Gauquelin CURA data parser.',
    '',
    'Data source: http://cura.free.fr/gauq/17archg.html',
    'Parses the 17 CURA-format Gauquelin data files (A1-A6, B1-B6, C1-C3, D1-D2, E1).',
    '',
    'CURA Fixed-Width Format',
    '-----------------------',
    'Each data line (after headers) follows this approximate layout:',
    '  Cols  1-4   record number (zero-padded integer)',
    '  Cols  5-24  last name (UPPER CASE, space-padded)',
    '  Cols 25-44  first name (mixed or upper case)',
    '  Col  45     gender (M or F)',
    '  Cols 46-53  DD MM YYYY',
    '  Cols 54-57  HH MM',
    '  Cols 58-72  city name',
    '  Cols 73-74  country code (FR, BE, DE, ...)',
    '  Cols 75-80  latitude (e.g. 4852N)',
    '  Cols 81-86  longitude (e.g. 00220E)',
    '',
    'Blind Pipeline Contract',
    '-----------------------',
    'Two intentionally separated output files are produced:',
    '',
    '  subjects_blind.json      - id, date, time, city, country, gender ONLY',
    '                             --> pass to 02_batch_calculate.py',
    '  subjects_occupation.json - id, occupation_group, occupation_detail ONLY',
    '                             --> KEEP SEPARATE until 04_analyze.py',
    '',
    'Usage',
    '-----',
    '    python 01_parse_gauquelin.py --data-dir ./cura_data --out-dir ./output',
    '    python 01_parse_gauquelin.py --files A1.txt A2.txt --out-dir ./output',
    '    python 01_parse_gauquelin.py --validate-split --out-dir ./output',
    '"""',
    '',
    'import argparse',
    'import json',
    'import logging',
    'import re',
    'import sys',
    'from collections import Counter',
    'from dataclasses import dataclass',
    'from pathlib import Path',
    'from typing import Dict, List, Optional, Tuple',
    '',
    'logging.basicConfig(',
    '    level=logging.INFO,',
    '    format="%(asctime)s [%(levelname)s] %(message)s",',
    '    datefmt="%Y-%m-%dT%H:%M:%S",',
    ')',
    'logger = logging.getLogger(__name__)',
    '',
    '',
    'CURA_SERIES_DETAIL: Dict[str, str] = {',
    '    "A1": "Sports Champions (French)",',
    '    "A2": "Sports Champions (European - Athletics)",',
    '    "A3": "Sports Champions (European - Ball Sports)",',
    '    "A4": "Sports Champions (European - Combat and Racing)",',
    '    "A5": "Sports Champions (European - Team Sports)",',
    '    "A6": "Sports Champions (European - Water Sports)",',
    '    "B1": "Physicians and Scientists",',
    '    "B2": "Military Officers",',
    '    "B3": "Painters and Artists",',
    '    "B4": "Actors and Performers",',
    '    "B5": "Musicians",',
    '    "B6": "Writers and Poets",',
    '    "C1": "Sports Champions (Replication Set 1)",',
    '    "C2": "Sports Champions (Replication Set 2)",',
    '    "C3": "Scientists (Replication Set)",',
    '    "D1": "Military Officers (Extended)",',
    '    "D2": "Journalists and Politicians",',
    '    "E1": "Executives and Clergy",',
    '}',
    '',
    'CURA_SERIES_GROUP: Dict[str, str] = {',
    '    "A1": "Athletes", "A2": "Athletes", "A3": "Athletes",',
    '    "A4": "Athletes", "A5": "Athletes", "A6": "Athletes",',
    '    "B1": "Scientists",',
    '    "B2": "Military",',
    '    "B3": "Artists",  "B4": "Artists",  "B5": "Artists",',
    '    "B6": "Writers",',
    '    "C1": "Athletes", "C2": "Athletes",',
    '    "C3": "Scientists",',
    '    "D1": "Military",',
    '    "D2": "Politicians",',
    '    "E1": "Executives",',
    '}',
]

f01.extend([
    '',
    '',
    '@dataclass',
    'class RawRecord:',
    '    """Full intermediate representation of one parsed Gauquelin subject."""',
    '    record_num: int',
    '    series: str',
    '    last_name: str',
    '    first_name: str',
    '    gender: str',
    '    day: int',
    '    month: int',
    '    year: int',
    '    hour: int',
    '    minute: int',
    '    city: str',
    '    country: str',
    '    lat_raw: str',
    '    lon_raw: str',
    '    occupation_detail: str',
    '    occupation_group: str',
    '',
    '    @property',
    '    def uid(self) -> str:',
    '        """Unique subject identifier: series + zero-padded record number."""',
    '        return f"{self.series}-{self.record_num:04d}"',
    '',
    '    @property',
    '    def date_str(self) -> str:',
    '        return f"{self.year:04d}-{self.month:02d}-{self.day:02d}"',
    '',
    '    @property',
    '    def time_str(self) -> str:',
    '        return f"{self.hour:02d}:{self.minute:02d}"',
    '',
    '',
    'class CURAParser:',
    '    """',
    '    Parser for CURA-format Gauquelin data files.',
    '',
    '    Parsing strategy:',
    '    1. Skip lines without a leading 4-digit record number.',
    '    2. Slice the name block (cols 4-49).',
    '    3. Apply DATE_TIME_RE after col 50 to locate date/time.',
    '    4. Parse the location tail via regex for lat/lon and country code.',
    '',
    '    CURA files are Latin-1 (ISO-8859-1) encoded.',
    '    """',
    '',
    '    _KNOWN_COUNTRIES = frozenset({',
    '        "FR", "BE", "DE", "IT", "ES", "GB", "US", "CH", "AT", "NL",',
    '        "PL", "RU", "SE", "NO", "DK", "PT", "HU", "CZ", "RO", "GR",',
    '        "AR", "BR", "AU", "CA", "MX", "JP", "IN", "ZA", "FI", "IE",',
    '        "YU", "CS", "DD", "SU",',
    '    })',
    '    _DATE_TIME_RE = re.compile(',
    '        r"(?P<day>\\d{1,2})\\s+(?P<month>\\d{1,2})\\s+(?P<year>\\d{4})\\s+"',
    '        r"(?P<hour>\\d{1,2})\\s+(?P<minute>\\d{1,2})"',
    '    )',
    '    _LAT_RE = re.compile(r"(\\d{2,4})\\s*([NS])", re.IGNORECASE)',
    '    _LON_RE = re.compile(r"(\\d{3,5})\\s*([EW])", re.IGNORECASE)',
    '',
    '    def __init__(self, series: str) -> None:',
    '        self.series = series',
    '        self.occupation_detail = CURA_SERIES_DETAIL.get(series, "Unknown")',
    '        self.occupation_group  = CURA_SERIES_GROUP.get(series, "Unknown")',
    '',
    '    def parse_file(self, filepath: Path) -> List[RawRecord]:',
    '        """Parse an entire CURA file; return a list of RawRecord objects."""',
    '        records: List[RawRecord] = []',
    '        error_count = 0',
    '        try:',
    '            with open(filepath, encoding="latin-1", errors="replace") as fh:',
    '                raw_lines = fh.readlines()',
    '        except OSError as exc:',
    '            logger.error("Cannot open %s: %s", filepath, exc)',
    '            return records',
    '        logger.info("  Parsing %s (%d lines)...", filepath.name, len(raw_lines))',
    '        for lineno, line in enumerate(raw_lines, start=1):',
    '            line = line.rstrip("\n\r")',
    '            if not line.strip() or not line[:4].strip().isdigit():',
    '                continue',
    '            rec = self._parse_line(line, lineno)',
    '            if rec is not None:',
    '                records.append(rec)',
    '            else:',
    '                error_count += 1',
    '                if error_count <= 10:',
    '                    logger.debug("  Skipped line %d: %r", lineno, line[:80])',
    '        logger.info("  %s -> %d records, %d skipped.",',
    '            filepath.name, len(records), error_count)',
    '        return records',
])

f01.extend([
    '',
    '    def _parse_line(self, line: str, lineno: int) -> Optional[RawRecord]:',
    '        """Parse one data line. Returns None on failure."""',
    '        try:',
    '            rec_str = line[:4].strip()',
    '            if not rec_str.isdigit():',
    '                return None',
    '            rec_num = int(rec_str)',
    '            name_block = line[4:50] if len(line) >= 50 else line[4:]',
    '            last_name, first_name = self._split_name(name_block)',
    '            gender_char = line[50:51].strip() if len(line) > 50 else "?"',
    '            gender = gender_char.upper() if gender_char.upper() in ("M", "F") else "?"',
    '            search_zone = line[51:] if len(line) > 51 else ""',
    '            dt_match = self._DATE_TIME_RE.search(search_zone)',
    '            if not dt_match:',
    '                return None',
    '            day    = int(dt_match.group("day"))',
    '            month  = int(dt_match.group("month"))',
    '            year   = int(dt_match.group("year"))',
    '            hour   = int(dt_match.group("hour"))',
    '            minute = int(dt_match.group("minute"))',
    '            if not (1 <= day <= 31 and 1 <= month <= 12 and 1800 <= year <= 2000):',
    '                return None',
    '            if not (0 <= hour <= 23 and 0 <= minute <= 59):',
    '                return None',
    '            tail_offset = 51 + dt_match.end()',
    '            tail = line[tail_offset:].strip() if len(line) > tail_offset else ""',
    '            city, country, lat_raw, lon_raw = self._parse_location_tail(tail)',
    '            return RawRecord(',
    '                record_num=rec_num, series=self.series,',
    '                last_name=last_name, first_name=first_name, gender=gender,',
    '                day=day, month=month, year=year,',
    '                hour=hour, minute=minute,',
    '                city=city, country=country,',
    '                lat_raw=lat_raw, lon_raw=lon_raw,',
    '                occupation_detail=self.occupation_detail,',
    '                occupation_group=self.occupation_group,',
    '            )',
    '        except Exception as exc:',
    '            logger.debug("  Line %d: %s", lineno, exc)',
    '            return None',
    '',
    '    @staticmethod',
    '    def _split_name(name_block: str) -> Tuple[str, str]:',
    '        """Split 46-char name block into (last_name, first_name)."""',
    '        last_raw  = name_block[:20].strip()',
    '        first_raw = name_block[20:40].strip()',
    '        if not first_raw and "  " in last_raw:',
    '            import re as _re',
    '            parts = _re.split(r"\\s{2,}", last_raw.strip(), maxsplit=1)',
    '            last_raw  = parts[0].strip()',
    '            first_raw = parts[1].strip() if len(parts) > 1 else ""',
    '        return (last_raw or "UNKNOWN"), (first_raw or "UNKNOWN")',
    '',
    '    def _parse_location_tail(self, tail: str) -> Tuple[str, str, str, str]:',
    '        """Extract (city, country, lat_raw, lon_raw) from line tail."""',
    '        lat_raw = lon_raw = ""',
    '        remaining = tail',
    '        lon_match = self._LON_RE.search(tail)',
    '        lat_match = self._LAT_RE.search(tail)',
    '        if lon_match:',
    '            lon_raw   = tail[lon_match.start():lon_match.end()]',
    '            remaining = tail[:lon_match.start()].strip()',
    '        if lat_match and lat_match.start() < (lon_match.start() if lon_match else len(tail)):',
    '            lat_raw   = tail[lat_match.start():lat_match.end()]',
    '            remaining = tail[:lat_match.start()].strip()',
    '        tokens  = remaining.split()',
    '        country = ""',
    '        city    = ""',
    '        if tokens:',
    '            if tokens[-1].upper() in self._KNOWN_COUNTRIES:',
    '                country = tokens[-1].upper()',
    '                city    = " ".join(tokens[:-1])',
    '            elif len(tokens) >= 2 and tokens[-2].upper() in self._KNOWN_COUNTRIES:',
    '                country = tokens[-2].upper()',
    '                city    = " ".join(tokens[:-2])',
    '            else:',
    '                city = " ".join(tokens)',
    '        return (city or "UNKNOWN"), (country or "??"), (lat_raw or "?"), (lon_raw or "?")',
])

