import pathlib
NL = chr(10)
BASE = pathlib.Path("validation/gauquelin")
BASE.mkdir(parents=True, exist_ok=True)


# === File 01: 01_parse_gauquelin.py ===
f01_lines = []
f01_lines.append('from __future__ import annotations')
f01_lines.append('')
f01_lines.append('"""')
f01_lines.append('01_parse_gauquelin.py - Gauquelin CURA data parser.')
f01_lines.append('')
f01_lines.append('Data source: http://cura.free.fr/gauq/17archg.html')
f01_lines.append('The CURA archive contains 17 files (A1-A6, B1-B6, C1-C3, D1-D2, E1).')
f01_lines.append('')
f01_lines.append('CURA Fixed-Width Format')
f01_lines.append('-----------------------')
f01_lines.append('Each data line (after file headers) follows this approximate layout:')
f01_lines.append('  Cols  1-4   record number (zero-padded integer)')
f01_lines.append('  Cols  5-24  last name (UPPER CASE, space-padded)')
f01_lines.append('  Cols 25-44  first name (mixed or upper case, space-padded)')
f01_lines.append('  Col  45     gender (M or F)')
f01_lines.append('  Cols 46-53  DD MM YYYY (birth date)')
f01_lines.append('  Cols 54-57  HH MM (birth hour and minute)')
f01_lines.append('  Cols 58-72  city name')
f01_lines.append('  Cols 73-74  country code (FR, BE, DE, IT, ...)')
f01_lines.append('  Cols 75-80  latitude  (e.g. 4852N)')
f01_lines.append('  Cols 81-86  longitude (e.g. 00220E)')
f01_lines.append('')
f01_lines.append('Column positions vary slightly across sub-series; this parser applies regex')
f01_lines.append('heuristics as a fallback for robustness across all 17 files.')
f01_lines.append('')
f01_lines.append('Blind Pipeline Contract')
f01_lines.append('-----------------------')
f01_lines.append('This script produces TWO intentionally separated output files:')
f01_lines.append('')
f01_lines.append('  subjects_blind.json')
f01_lines.append('    Fields: id, date, time, city, country, gender')
f01_lines.append('    No names. No occupation data.')
f01_lines.append('    --> Safe to pass to 02_batch_calculate.py')
f01_lines.append('')
f01_lines.append('  subjects_occupation.json')
f01_lines.append('    Fields: id, occupation_group, occupation_detail')
f01_lines.append('    MUST NOT be passed to 02_batch_calculate.py.')
f01_lines.append('    --> Merged only in 04_analyze.py, after all calculations are complete.')
f01_lines.append('')
f01_lines.append('Usage')
f01_lines.append('-----')
f01_lines.append('    python 01_parse_gauquelin.py --data-dir ./cura_data --out-dir ./output')
f01_lines.append('    python 01_parse_gauquelin.py --files A1.txt A2.txt --out-dir ./output')
f01_lines.append('    python 01_parse_gauquelin.py --validate-split --out-dir ./output')
f01_lines.append('"""')
f01_lines.append('')
f01_lines.append('import argparse')
f01_lines.append('import json')
f01_lines.append('import logging')
f01_lines.append('import re')
f01_lines.append('import sys')
f01_lines.append('from collections import Counter')
f01_lines.append('from dataclasses import dataclass')
f01_lines.append('from pathlib import Path')
f01_lines.append('from typing import Dict, List, Optional, Tuple')
f01_lines.append('')
f01_lines.append('logging.basicConfig(')
f01_lines.append('    level=logging.INFO,')
f01_lines.append('    format="%(asctime)s [%(levelname)s] %(message)s",')
f01_lines.append('    datefmt="%Y-%m-%dT%H:%M:%S",')
f01_lines.append(')')
f01_lines.append('logger = logging.getLogger(__name__)')
f01_lines.append('')
f01_lines.append('')
f01_lines.append('# ---------------------------------------------------------------------------')
f01_lines.append('# Series metadata')
f01_lines.append('# ---------------------------------------------------------------------------')
f01_lines.append('')
f01_lines.append('CURA_SERIES_DETAIL: Dict[str, str] = {')
f01_lines.append('    "A1": "Sports Champions (French)",')
f01_lines.append('    "A2": "Sports Champions (European - Athletics)",')
f01_lines.append('    "A3": "Sports Champions (European - Ball Sports)",')
f01_lines.append('    "A4": "Sports Champions (European - Combat and Racing)",')
f01_lines.append('    "A5": "Sports Champions (European - Team Sports)",')
f01_lines.append('    "A6": "Sports Champions (European - Water Sports)",')
f01_lines.append('    "B1": "Physicians and Scientists",')
f01_lines.append('    "B2": "Military Officers",')
f01_lines.append('    "B3": "Painters and Artists",')
f01_lines.append('    "B4": "Actors and Performers",')
f01_lines.append('    "B5": "Musicians",')
f01_lines.append('    "B6": "Writers and Poets",')
f01_lines.append('    "C1": "Sports Champions (Replication Set 1)",')
f01_lines.append('    "C2": "Sports Champions (Replication Set 2)",')
f01_lines.append('    "C3": "Scientists (Replication Set)",')
f01_lines.append('    "D1": "Military Officers (Extended)",')
f01_lines.append('    "D2": "Journalists and Politicians",')
f01_lines.append('    "E1": "Executives and Clergy",')
f01_lines.append('}')
f01_lines.append('')
f01_lines.append('CURA_SERIES_GROUP: Dict[str, str] = {')
f01_lines.append('    "A1": "Athletes", "A2": "Athletes", "A3": "Athletes",')
f01_lines.append('    "A4": "Athletes", "A5": "Athletes", "A6": "Athletes",')
f01_lines.append('    "B1": "Scientists",')
f01_lines.append('    "B2": "Military",')
f01_lines.append('    "B3": "Artists",  "B4": "Artists",  "B5": "Artists",')
f01_lines.append('    "B6": "Writers",')
f01_lines.append('    "C1": "Athletes", "C2": "Athletes",')
f01_lines.append('    "C3": "Scientists",')
f01_lines.append('    "D1": "Military",')
f01_lines.append('    "D2": "Politicians",')
f01_lines.append('    "E1": "Executives",')
f01_lines.append('}')
