'from __future__ import annotations',
'',
'"""',
'01_parse_gauquelin.py - Gauquelin CURA data parser.',
'',
'Parses the 17 CURA-format Gauquelin data files (A1-A6, B1-B6, C1-C3, D1-D2, E1).',
'Data source: http://cura.free.fr/gauq/17archg.html',
'',
'CURA Fixed-Width Format',
'-----------------------',
'After a header block each data line follows this approximate layout:',
'  Cols  1-4   record number (zero-padded integer)',
'  Cols  5-24  last name (UPPER CASE, space-padded)',
'  Cols 25-44  first name (mixed or upper case, space-padded)',
'  Col  45     gender (M or F)',
'  Cols 46-53  DD MM YYYY',
'  Cols 54-57  HH MM (birth hour and minute)',
'  Cols 58-72  city name',
'  Cols 73-74  country code (FR, BE, DE, IT, ...)',
'  Cols 75-80  latitude  (e.g. 4852N)',
'  Cols 81-86  longitude (e.g. 00220E)',
'',
'Column positions vary slightly across sub-series; this parser applies regex',
'heuristics as a fallback for robustness.',
'',
'Blind Pipeline Contract',
'-----------------------',
'This script INTENTIONALLY produces two separate output files:',
'',
'  subjects_blind.json      - id, date, time, city, country, gender ONLY',
'                             No names. No occupation data.',
'                             --> pass to 02_batch_calculate.py',
'',
'  subjects_occupation.json - id, occupation_group, occupation_detail ONLY',
'                             MUST NOT be passed to 02_batch_calculate.py.',
'                             --> keep SEPARATE until 04_analyze.py',
'',
'Usage',
'-----',
'    python 01_parse_gauquelin.py --data-dir ./cura_data --out-dir ./output',
'    python 01_parse_gauquelin.py --files A1.txt A2.txt --out-dir ./output',
'    python 01_parse_gauquelin.py --validate-split --out-dir ./output',
'"""',
'',
'import argparse',
'import json',
'import logging',
'import re',
'import sys',
'from collections import Counter',
'from dataclasses import dataclass',
'from pathlib import Path',
'from typing import Dict, List, Optional, Tuple',
'',
'logging.basicConfig(',
'    level=logging.INFO,',
'    format="%(asctime)s [%(levelname)s] %(message)s",',
'    datefmt="%Y-%m-%dT%H:%M:%S",',
')',
'logger = logging.getLogger(__name__)',
'',
