import pathlib
NL = chr(10)
BASE = pathlib.Path("validation/gauquelin")
BASE.mkdir(parents=True, exist_ok=True)
L = []
L.append('from __future__ import annotations')
L.append('"""')
L.append('01_parse_gauquelin.py')
L.append('Parses Gauquelin CURA-format data files (A1-A6, B1-B6, C1-C3, D1-D2, E1).')
L.append('Source: http://cura.free.fr/gauq/17archg.html')
L.append('')
L.append('CURA Fixed-Width Format:')
L.append('  Cols 1-4   : record number')
L.append('  Cols 5-24  : last name (uppercase)')
L.append('  Cols 25-44 : first name')
L.append('  Col  45    : gender (M/F)')
L.append('  Cols 46-53 : DD MM YYYY (birth date)')
L.append('  Cols 54-57 : HH MM (birth time)')
L.append('  Cols 58-72 : city name')
L.append('  Cols 73-74 : country code')
L.append('  Cols 75-80 : latitude (e.g. 4852N)')
L.append('  Cols 81-86 : longitude (e.g. 00220E)')
L.append('')
L.append('Produces two split files:')
L.append('  subjects_blind.json      - id, date, time, city, country, gender ONLY')
L.append('  subjects_occupation.json - id, occupation_group, occupation_detail ONLY')
L.append('"""')
L.append('import argparse, json, logging, re, sys')
L.append('from collections import Counter')
L.append('from dataclasses import dataclass')
L.append('from pathlib import Path')
L.append('from typing import Dict, List, Optional, Tuple')
L.append('')
L.append('logging.basicConfig(level=logging.INFO,')
L.append('    format="%(asctime)s [%(levelname)s] %(message)s",')
L.append('    datefmt="%Y-%m-%dT%H:%M:%S")')
L.append('logger = logging.getLogger(__name__)')
L.append('')
L.append('# Series metadata')
L.append('CURA_SERIES_DETAIL: Dict[str, str] = {')
L.append('    "A1": "Sports Champions (French)",')
L.append('    "A2": "Sports Champions (European - Athletics)",')
L.append('    "A3": "Sports Champions (European - Ball Sports)",')
L.append('    "A4": "Sports Champions (European - Combat and Racing)",')
L.append('    "A5": "Sports Champions (European - Team Sports)",')
L.append('    "A6": "Sports Champions (European - Water Sports)",')
L.append('    "B1": "Physicians and Scientists",')
L.append('    "B2": "Military Officers",')
L.append('    "B3": "Painters and Artists",')
L.append('    "B4": "Actors and Performers",')
L.append('    "B5": "Musicians",')
L.append('    "B6": "Writers and Poets",')
L.append('    "C1": "Sports Champions (Replication Set 1)",')
L.append('    "C2": "Sports Champions (Replication Set 2)",')
L.append('    "C3": "Scientists (Replication Set)",')
L.append('    "D1": "Military Officers (Extended)",')
L.append('    "D2": "Journalists and Politicians",')
L.append('    "E1": "Executives and Clergy",')
L.append('}')
L.append('')
L.append('CURA_SERIES_GROUP: Dict[str, str] = {')
L.append('    "A1": "Athletes", "A2": "Athletes", "A3": "Athletes",')
L.append('    "A4": "Athletes", "A5": "Athletes", "A6": "Athletes",')
L.append('    "B1": "Scientists",')
L.append('    "B2": "Military",')
L.append('    "B3": "Artists",  "B4": "Artists",  "B5": "Artists",')
L.append('    "B6": "Writers",')
L.append('    "C1": "Athletes", "C2": "Athletes",')
L.append('    "C3": "Scientists",')
L.append('    "D1": "Military",')
L.append('    "D2": "Politicians",')
L.append('    "E1": "Executives",')
L.append('}')
